const constants = {
  APPLICATION_ID: 45,
  refreshOptions: [
    {
      value: '0',
      description: 'Auto Refresh Off',
    },
    {
      value: '2',
      description: 'Every 2 min',
    },
    {
      value: '5',
      description: 'Every 5 min',
    },
    {
      value: '10',
      description: 'Every 10 min',
    },
  ],
  FETCH_CONSOLIDATED_ACCUMULATOR_RISK_FILTER: 'CRM::FETCH_CONSOLIDATED_ACCUMULATOR_RISK_FILTER',
  FETCH_CONSOLIDATED_ACCUMULATOR_RISK_FILTER_SUCCEEDED: 'CRM::FETCH_CONSOLIDATED_ACCUMULATOR_RISK_FILTER_SUCCEEDED',
  FETCH_CONSOLIDATED_ACCUMULATOR_RISK_FILTER_FAILED: 'CRM::FETCH_CONSOLIDATED_ACCUMULATOR_RISK_FILTER_FAILED',
  FETCH_CONSOLIDATED_ACCUMULATOR_RISK_DETAILS: 'CRM::FETCH_CONSOLIDATED_ACCUMULATOR_RISK_DETAILS',
  FETCH_CONSOLIDATED_ACCUMULATOR_RISK_DETAILS_SUCCEEDED: 'CRM::FETCH_CONSOLIDATED_ACCUMULATOR_RISK_DETAILS_SUCCEEDED',
  FETCH_CONSOLIDATED_ACCUMULATOR_RISK_DETAILS_FAILED: 'CRM::FETCH_CONSOLIDATED_ACCUMULATOR_RISK_DETAILS_FAILED',
  FETCH_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS: 'CRM::FETCH_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS',
  FETCH_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS_SUCCEEDED:
    'CRM::FETCH_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS_SUCCEEDED',
  FETCH_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS_FAILED:
    'CRM::FETCH_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS_FAILED',
  RELOAD_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS: 'CRM::RELOAD_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS',
  RELOAD_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS_SUCCEEDED:
    'CRM::RELOAD_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS_SUCCEEDED',
  RELOAD_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS_FAILED:
    'CRM::RELOAD_CONSOLIDATED_ACCUMULATOR_RISK_ARBET_DETAILS_FAILED',
  UPDATE_COMBINATION_LIABILITY_INDICATOR: 'CRM::UPDATE_COMBINATION_LIABILITY_INDICATOR',
  PUT_COMBINATION_LIABILITY_INDICATOR: 'CRM::PUT_COMBINATION_LIABILITY_INDICATOR',
  PUT_COMBINATION_LIABILITY_INDICATOR_SUCCEEDED: 'CRM::PUT_COMBINATION_LIABILITY_INDICATOR_SUCCEEDED',
  PUT_COMBINATION_LIABILITY_INDICATOR_FAILED: 'CRM::PUT_COMBINATION_LIABILITY_INDICATOR_FAILED',
  REMOVE_COMBINATION_LIABILITY_INDICATOR: 'CRM::REMOVE_COMBINATION_LIABILITY_INDICATOR',
  SET_TOP_PANEL_DETAILS: 'CRM::SET_TOP_PANEL_DETAILS',
  DISABLE_AUTOREFRESH: 'CRM::DISABLE_AUTOREFRESH',
  SET_MAIN_PANEL_SELECTED_ITEM: 'CRM::SET_MAIN_PANEL_SELECTED_ITEM',
  SET_AUTOREFRESH: 'CRM::SET_AUTOREFRESH',
  SET_BET_TYPE: 'CRM::SET_BET_TYPE',
  SET_BLOCKING_TYPE_MAP: 'CRM::SET_BLOCKING_TYPE_MAP',
  TOGGLE_BLOCKING_RULE_MODAL: 'CRM::TOGGLE_BLOCKING_RULE_MODAL',
  INITIALIZE_DEFAULT: 'CRM::INITIALIZE_DEFAULT',
  SET_FLAG_ITEM_MODIFIED: 'CRM::SET_FLAG_ITEM_MODIFIED',
  REMOVE_FLAG_ITEM_MODIFIED: 'CRM::REMOVE_FLAG_ITEM_MODIFIED',
  SET_LIMIT_CHANGE: 'CRM::SET_LIMIT_CHANGE',
  RESET_LIMIT_CHANGE: 'CRM::RESET_LIMIT_CHANGE',
  FETCH_PROFILE_FLAGS: 'CRM::FETCH_PROFILE_FLAGS',
  FETCH_PROFILE_FLAGS_SUCCEEDED: 'CRM::FETCH_PROFILE_FLAGS_SUCCEEDED',
  FETCH_PROFILE_FLAGS_FAILED: 'CRM::FETCH_PROFILE_FLAGS_FAILED',
  RESET_PROFILE_FLAGS: 'CRM::RESET_PROFILE_FLAGS',
  SET_BLOCKING_RULE: 'CRM::SET_BLOCKING_RULE',
  SET_BLOCKING_RULE_SUCCEEDED: 'CRM::SET_BLOCKING_RULE_SUCCEEDED',
  SET_BLOCKING_RULE_FAILED: 'CRM::SET_BLOCKING_RULE_FAILED',

  SORT_ACCUMULATOR_DATA: 'CRM::SORT_ACCUMULATOR_DATA',
  TOGGLE_FILTER_MODAL: 'CRM::TOGGLE_FILTER_MODAL',

  SET_SPORT_FILTER_TYPE: 'CRM::SET_SPORT_FILTER_TYPE',

  FETCH_EVENT_PATHS_FILTER: 'CRM::FETCH_EVENT_PATHS_FILTER',
  FETCH_EVENT_PATHS_FILTER_SUCCEEDED: 'CRM::FETCH_EVENT_PATHS_FILTER_SUCCEEDED',
  FETCH_EVENT_PATHS_FILTER_FAILED: 'CRM::FETCH_EVENT_PATHS_FILTER_FAILED',

  FETCH_EVENT_PATHS_CHILD_FILTER: 'CRM::FETCH_EVENT_PATHS_CHILD_FILTER',
  FETCH_EVENT_PATHS_CHILD_FILTER_SUCCEEDED: 'CRM::FETCH_EVENT_PATHS_CHILD_FILTER_SUCCEEDED',
  FETCH_EVENT_PATHS_CHILD_FILTER_FAILED: 'CRM::FETCH_EVENT_PATHS_CHILD_FILTER_FAILED',

  FETCH_EVENT_PATH_EVENTS_FILTER: 'CRM::FETCH_EVENT_PATH_EVENTS_FILTER',
  FETCH_EVENT_PATH_EVENTS_FILTER_SUCCEEDED: 'CRM::FETCH_EVENT_PATH_EVENTS_FILTER_SUCCEEDED',
  FETCH_EVENT_PATH_EVENTS_FILTER_FAILED: 'CRM::FETCH_EVENT_PATH_EVENTS_FILTER_FAILED',

  FETCH_EVENT_PATH_EVENTS_FILTER: 'CRM::FETCH_EVENT_PATH_EVENTS_FILTER',
  FETCH_EVENT_PATH_EVENTS_FILTER_SUCCEEDED: 'CRM::FETCH_EVENT_PATH_EVENTS_FILTER_SUCCEEDED',
  FETCH_EVENT_PATH_EVENTS_FILTER_FAILED: 'CRM::FETCH_EVENT_PATH_EVENTS_FILTER_FAILED',

  FETCH_EVENT_PATH_MARKETS_FILTER: 'CRM::FETCH_EVENT_PATH_MARKETS_FILTER',
  FETCH_EVENT_PATH_MARKETS_FILTER_SUCCEEDED: 'CRM::FETCH_EVENT_PATH_MARKETS_FILTER_SUCCEEDED',
  FETCH_EVENT_PATH_MARKETS_FILTER_FAILED: 'CRM::FETCH_EVENT_PATH_MARKETS_FILTER_FAILED',

  FETCH_EVENT_PATH_OUTCOMES_FILTER: 'CRM::FETCH_EVENT_PATH_OUTCOMES_FILTER',
  FETCH_EVENT_PATH_OUTCOMES_FILTER_SUCCEEDED: 'CRM::FETCH_EVENT_PATH_OUTCOMES_FILTER_SUCCEEDED',
  FETCH_EVENT_PATH_OUTCOMES_FILTER_FAILED: 'CRM::FETCH_EVENT_PATH_OUTCOMES_FILTER_FAILED',

  TOGGLE_EVENT_PATH_FILTER: 'CRM::TOGGLE_EVENT_PATH_FILTER',
  SET_EVENT_PATH_SELECTED_FILTER: 'CRM::SET_EVENT_PATH_SELECTED_FILTER',
  UPDATE_FILTERS: 'CRM::UPDATE_FILTERS',
  SHOULD_ITEM_RESET: 'CRM::SHOULD_ITEM_RESET',
}

export const riskActionTypes = {
  NONE: 'None',
  REJECT_50: 'Reject 50',
  REJECT_100: 'Reject 100',
  REFER_ALL: 'Refer All',
  REFER_50: 'Refer 50',
  REFER_100: 'Refer 100',
  BLOCK_SPECIFIC_COMBINATION: 'Block Specific Combination',
  BLOCK_ANY_COMBINATION: 'Block Any Combination',
}

export const limitCombinationTypes = {
  STAKE: 'STAKE',
  PAYOUT: 'PAYOUT',
  LIABILITY: 'LIABILITY',
}

export const betTypes = ['None', 'Single', 'Double', 'Treble', '4 Fold Accumulator']

export const betStatus = {
  Pending: 'PENDING',
  Won: 'WON',
  Lost: 'LOST',
  'Last Leg': 'LAST_LEG',
  Void: 'VOID',
  Dynamic: 'DYNAMIC',
  Unknown: 'UNKNOWN',
}

export const blockingStatus = ['ANY', 'SPECIFIC', 'NONE']

export const settledStatus = {
  Settled: 'SETTLED',
  'Not Settled': 'NOT_SETTLED',
  Any: 'ANY',
}

export default constants
